INSERT INTO public.users ("username", "hashedPassword", "email") VALUES ('udaibirv','$argon2i$v=19$m=4096,t=3,p=1$h7icQD/xZr8akZsX+hNA0A$h68atJWyjvunAwNOpSpMfg9sPvoMQ6dKwoh0dJhurWA', 'uvirk@yahoo.com');
INSERT INTO public.recipes ("recipeName", "equipment", "recipeOrigin", "imageUrl","userId") VALUES ('Yellow Lentils', 'Simple Pot, Small Pan', 'Lentil Soup (Daal) is a very common dish served throughout all of India. It is good for digestion and also serves as a strong source of protein in the mostly vegetarian diet of Indian cuisine. It can be served as a soup, and also with rice, or roti (flatbread).', 'https://headbangerskitchen.com/wp-content/uploads/2019/07/YELLOWDALTADKA-Vertical.jpg',1);
INSERT INTO public.recipes ("recipeName", "equipment", "recipeOrigin", "imageUrl","userId") VALUES ('Jeera Aloo', 'Simple Pan', 'Jeera Aloo is a popular North Indian dish due to it''s easy nature to make, as well as it''s deliciousness. This is a perfect dish for a picnic day, packed lunches for your kids, and a quick lunch meal. It can be eaten with either a traditional roti (flatbread) or even a paratha. ', 'https://www.cookwithmanali.com/wp-content/uploads/2015/09/Jeera-Aloo-Recipe-Indian-500x500.jpg',1);
INSERT INTO public.recipes ("recipeName", "equipment", "recipeOrigin", "imageUrl","userId") VALUES ('Rajma', 'Pressure Cooker, Small Pan', 'Rajma, or kidney beans, is a very popular dish from Northern India. It is often served during lunch time and can be eaten with roti (flatbread) but more often with rice. Rajma is also a great source of both protein and fiber. It can also be eaten with a side of yogurt to balance out the spices that go into making the dish. Before beginning to make Rajma it is important to soak them in water for at least 4-6 hours.', 'https://www.cubesnjuliennes.com/wp-content/uploads/2020/06/Authentic-Punjabi-Rajma-Recipe.jpg',1);
INSERT INTO public.recipes ("recipeName", "equipment", "recipeOrigin", "imageUrl","userId") VALUES ('Kheer (Rice Pudding)', 'Deep Bottomed Pot', 'Kheer is a popular desert throughout all of India. Made with rice and milk, it is often served during weddings, birthdays, and all special occasions. It can be served both cold and hot depending on the weather. ', 'https://www.cookwithmanali.com/wp-content/uploads/2017/06/Indian-Rice-Kheer-500x375.jpg',1);
INSERT INTO public.recipes ("recipeName", "equipment", "recipeOrigin", "imageUrl","userId") VALUES ('Veggie Pulao', 'Deep Bottomed Pot', 'Popular Northern Indian dish often served during lunch or dinner. Adding yogurt as a side dish is often a popular combination as it can balance out some of the spice. Pulao is commonly made for birthdays, weddings, and most special occasions. ', 'https://www.whiskaffair.com/wp-content/uploads/2019/05/Veg-Pulao-1-3.jpg',1);
INSERT INTO public.recipes ("recipeName", "equipment", "recipeOrigin", "imageUrl","userId") VALUES ('Mint Chutney', 'Food Processor ', 'Mint Chutney is a very popular condiment throughout all of India. It is often paired with snacks such as samosas and pakoras, as well as dishes like Rajma and Chicken. The mint base helps in digestion and brings a nice aroma to any dinner table.  ', 'https://spicecravings.com/wp-content/uploads/2020/09/Mint-Chutney-1.jpg',1);
INSERT INTO public.directions ("instruction", "recipeId", "stepNumber") VALUES ('Add 3 cups of water to the pot and bring it to boil. Add washed lentils into the pot and add the salt, turmeric, and let it cook for 20 minutes on medium heat with pot covered. When lentils are soft and done, mix it well and turn heat off. In the pan, take 2 tbsp oil and let it heat up. Chop the onions and add cook it until they are golden brown. Add the ginger and garlic and cook it for one minute. Chop the tomatoes and add them and cook until they are soft. Now add black pepper and garam masala, and turn the heat off. Pour the mixture over the lentils in the pot and mix it well. Enjoy!  ',1, 1);
INSERT INTO public.directions ("instruction", "recipeId","stepNumber") VALUES ('Pour oil into pan and let it heat up. Add cumin seeds and wait till they crackle. Then add chopped potatoes (small cubes) and cook until the edges turn brown. Bring the heat to low and add turmeric powder, salt, and red chili powder. Mix all of them well. Cover the pan and cook it for about 5-7 minutes while occasionally stirring. When potatoes are cooked, turn the heat off and add the chaat masala and cilantro for garnish. Enjoy! ', 2,1);
INSERT INTO public.directions ("instruction", "recipeId", "stepNumber") VALUES ('Wash the soaked kidney beans well and add 4 cups of water to the pressure cooker, bring to boil. Add the beans and salt, place the lid, and let it cook for 3 whistles on medium heat. Meanwhile, grind up the onion and pour oil onto the small pan. When the oil is hot, add the cumin seeds and wait until they begin to crackle. After, add the onions that were ground and cook it until they are light brown. Now add the ginger + garlic paste, as well as the green chillies on low to medium heat and cook for 1 minute. Now add the chopped tomatoes and cook until it is soft. Now, add turmeric powder, garam masala, and the rajma masala. Cook for about 40 seconds and mix well. Add this mixture to the beans in the pressure cooker and let it simmer on low heat for 5 minutes. Serve with either rice or roti. Enjoy!',3,1);
INSERT INTO public.directions ( "instruction", "recipeId", "stepNumber") VALUES ('Wash the rice 2-3 times and then soak them for 20 minutes. Pour the milk in the pot and bring to boil on medium heat, while stirring occasionally. After draining the rice, add the rice into the milk and stir well and bring the heat to low. Let it cook until the rice is soft and the mixture is thick. Next, add the sugar and cook for at least 3-4 minutes. Make sure to scrape the sides and stir often. Add the almonds and cardamum powder and turn the heat off. When it is no longer runny, you are done. Enjoy!',4,1);
INSERT INTO public.directions ( "instruction", "recipeId","stepNumber") VALUES ('Wash the rice 2-3 times and soak in water for 30 minutes. Add the oil to the pot and when oil is hot, add the cardamum, bay leaves, pepper, cloves and cinnamon stick. Cook on low for about 10 seconds. Add the ginger and cook for another 30 seconds. Add the chopped vegetables and cook for about 2 minutes while stirring occasionally. Now add the water and then add the rice, salt, gently mix everything. Bring it to boil on medium-high heat and then cover the pot and then bring heat to low. Let it cook for about 10-15 minutes until the rice is tender and water is absorbed. Enjoy! ',5, 1);
INSERT INTO public.directions ( "instruction", "recipeId","stepNumber") VALUES ('Place all the ingredients in the food processor. Grind until it becomes a thick paste. Simple and quick, Enjoy!', 6, 1);
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (1,'Yellow Lentils', '1/4 Cup');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (1,'Salt','1/2 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (1,'Garam Masala','1/4 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (1,'Black Pepper','1/4 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (1,'Onion','1');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (1,'Tomato','1');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (1,'Chopped Green Cilantro ', '1 tbsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (1,'Ginger','1 inch piece ');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (1,'Garlic','2 Cloves');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (2,'Potatoes','3');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (2,'Cumin Seeds','1 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (2,'Salt','1/2 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (2,'Red Chili Powder','1/4 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (2,'Turmeric Powder','1/4 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (2,'Chaat Masala','1/4 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (2,'Cooking Oil','2 tbsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (3,'Kidney Beans','1 cup ');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (3,'Onion','1');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (3,'Ginger Paste','1 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (3,'Garlic paste','1 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (3,'Chopped Green Chili','1 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (3,'Tomato','1');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (3,'Salt','1/2 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (3,'Turmeric Powder','1/4 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (3,'Garam Masala','1/2 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (3,'Cumin Seeds','1/2 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (3,'Cooking Oil','2 tbsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (3,'Rajma Masala','1 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (4,'Full Fat Milk','4 cups');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (4,'Basmati Rice','1/4 cup');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (4,'Sugar','1/2 cup');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (4,'Cardamum Powder','1/4 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (4,'Chopped Almonds','1 tbsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Basmati Rice','1 cup');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Water','2 cups');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Salt','3/4 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Chopped Ginger','1 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Chopped Carrots','1/4 cup');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Peas','1/4 cup');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Chopped Green Beans','1/4 cup');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Bay Leaves','2');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Green Cardamum','2');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Cloves','4');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Small Cinnamon Stick','1');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Black Pepper','1/4 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Cumin Seeds','1/2 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Garam Masala','1/2 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (5,'Cooking Oil','1 tbsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (6,'Cilantro','1 bunch');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (6,'Fresh Mint Leaves','1 cup');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (6,'Green Chili ','1');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (6,'Salt','1/2 tsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (6,'Chopped Onion','1');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (6,'Lemon Juice','1 tbsp');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (6,'Ice Cubes','2');
INSERT INTO public.ingredients ("recipeId","name", "amount") VALUES (6,'Sugar','1/4 tsp');
